[package]
name = "rust-checks"
version = "0.0.0"
authors = ["Robert T. McGibbon <rmcgibbo@gmail.com>"]
edition = "2021"

[dependencies]
codespan = "0.12"
regex = "1"
rnix = "0.12"
rowan = { version = "0.15", features = [ "serde1" ] }
serde = { workspace = true }
serde_json = { workspace = true }
