name: CI

on:
  pull_request:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        # Nix fails to load the flake using flake-compat otherwise.
        fetch-depth: 0

    - name: Install Nix
      uses: cachix/install-nix-action@v31

    - name: Run tests
      run: nix develop -c cargo test
