name: CI

on:
  pull_request:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v12

    - name: Run tests
      run: nix run -c ./run-tests.py

  integration_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-20.09

    - name: Run tests
      run: |
        mkdir -p ~/.config/nixpkgs/
        echo '{ allowUnfree = true; }' > ~/.config/nixpkgs/config.nix
        nix run -c ./integration-tests/test-nixpkgs.py -f '<nixpkgs>'
