name: CI

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v27
      with:
        install_url: https://releases.nixos.org/nix/nix-2.17.0/install

    - name: Nix config
      run: |
        echo "============================"
        cat /etc/nix/nix.conf
        echo "============================"

    - name: Run tests
      run: nix shell -c ./run-tests.py
